[phases.setup]
nixPkgs = ['python311', 'gcc', 'python311Packages.pip']

[phases.install]
cmds = ['python -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT main:app'

[providers]
python = '3.11'
