name: Auto Deploy to Namecheap
on:
  push:
    branches: [production]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Namecheap
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /public_html/banku-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            # Restart your app if needed
            echo "Deployment completed successfully!"
