name: Auto Deploy to Namecheap
on:
  push:
    branches: [production]
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Namecheap via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_DIRECTORY }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.venv/**
            **/venv/**
            **/__pycache__/**
            **/.env
            **/logs/**
            **/instance/**
            **/.github/**
            **/README.md
            **/PROJECT_SUMMARY.md
            **/templates.zip
